### ISSUE TITLE
Author/Text Collection

### ISSUE THREAD

**Issue by transfluxus** [mrzl/ECO#126]
claus pias [done]
lacan [impossible to get text]
clarice lispector
heisenberg [only one found]
gottfried günther [one]
conrad zuse [one]
von neumann [cant find]
max planck
rene descartes

**Comment by mrzl** [comment]
joseph weizenbaum

**Comment by mrzl** [comment]
noel caroll

**Comment by mrzl** [comment]
margaret mead
