### ISSUE TITLE
Can Spacy.io be helpful?

### ISSUE THREAD

**Issue by mrzl** [mrzl/ECO#153]
https://spacy.io/

**Comment by transfluxus** [comment]
it is used as an  backend in rasa_nlu together with scikit-learn. the option to spaCy + scikit-learn is MITIE:  https://github.com/mit-nlp/MITIE

**Comment by mrzl** [comment]
kühl, dann kann die issue ja zu und wir machen daran hier weiter: https://github.com/mrzl/ECO/issues/160
