### ISSUE TITLE
Pdf collections

### ISSUE THREAD

**Issue by transfluxus** [mrzl/ECO#82]
http://www.meetopia.net/virus/pdf-ps_db/

**Comment by mrzl** [comment]
soll ich einfach mal ein paar ausgewählte runterladen?

**Comment by mrzl** [comment]
downloaded:
john_perry_barlow-a_declaration_of_the_independence_of_cyberspace.pdf
cae-recombinant_theater.pdf
marion_hamm-indymedia_concatenations_of_physical_and_virtual_space.pdf
kazys_varnelis-the_rise_of_network_culture.pdf
lev_manovich-the_anti_sublime_ideal_in_data_art.pdf
michel_bauwens-p2p_and_human_evolution.pdf
michel_bauwens-the_political_economy_of_peer_production.pdf
wark_mckenzie-a_hacker_manifesto.pdf
neal_stephenson-in_the_beginning_was_the_command_line.pdf
sherry_turkle-how_computers_change_the_way_we_think.pdf
sherry_turkle-the_second_self_computers_and_the_human_spirit.pdf
warren_sack-network_aesthetics.pdf
warren_sack_aesthetics_of_information_visualization.pdf
vannevar_bush-as_we_may_think.pdf
matteo_pasquinelli-radical_machines_against_the_techno_empire.pdf
